/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme1;

import frm.Ugovor.PretragaUgovora;
import frm.Ugovor.DodajUgovor;
import domen.Administrator;
import frm.Klijent.DodajKlijenta;
import frm.Klijent.PretragaKlijenta;
import frm.Usluge.DodajUslugu;
import frm.Usluge.PretragaUsluga;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import sesija.Sesija;

/**
 *
 * @author Lenovo
 */
public class Glavna extends javax.swing.JFrame {

    /**
     * Creates new form Glavna
     */
    
    Administrator ulogovani;
    
    public Glavna() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Meni");
        this.ulogovani = Sesija.getInstance().getUlogovani();
        lblAdmn.setText("Ulogovani administrator: " + ulogovani);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKlijent = new javax.swing.JButton();
        btnUgovori = new javax.swing.JButton();
        btnOdjava = new javax.swing.JButton();
        lblAdmn = new javax.swing.JLabel();
        btnUsluge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btnKlijent.setText("Klijenti");
        btnKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlijentActionPerformed(evt);
            }
        });

        btnUgovori.setText("Ugovori");
        btnUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgovoriActionPerformed(evt);
            }
        });

        btnOdjava.setText("Odjavi se");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        lblAdmn.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblAdmn.setText("jLabel1");

        btnUsluge.setText("Usluge");
        btnUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUslugeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAdmn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAdmn)
                .addGap(18, 18, 18)
                .addComponent(btnKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnUgovori, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlijentActionPerformed
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem dodajKlijenta = new JMenuItem("Dodaj klijenta");
        JMenuItem pretragaKlijenta = new JMenuItem("Pronađi klijenta");

        dodajKlijenta.addActionListener(e -> {
            new DodajKlijenta(this, true).setVisible(true);
        });

        pretragaKlijenta.addActionListener(e -> {
            new PretragaKlijenta(this, true).setVisible(true);
        });

        popupMenu.add(dodajKlijenta);
        popupMenu.add(pretragaKlijenta);

        popupMenu.show(btnKlijent, btnKlijent.getWidth(), 0);
    }//GEN-LAST:event_btnKlijentActionPerformed

    private void btnUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgovoriActionPerformed
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem dodajUgovor = new JMenuItem("Dodaj ugovor");
        JMenuItem pretragaUgovora = new JMenuItem("Pronađi ugovor");

        dodajUgovor.addActionListener(e -> {
            new DodajUgovor(this, true).setVisible(true);
        });

        pretragaUgovora.addActionListener(e -> {
            new PretragaUgovora(this, true).setVisible(true);
        });

        popupMenu.add(dodajUgovor);
        popupMenu.add(pretragaUgovora);

        popupMenu.show(btnUgovori, btnUgovori.getWidth(), 0);
    }//GEN-LAST:event_btnUgovoriActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        JPanel panel = new JPanel();
        panel.setBackground(Color.PINK);
        
        JLabel label = new JLabel("Da li ste sigurni da zelite da se odjavite sa sistema?");
                panel.add(label);
        
        int result = JOptionPane.showConfirmDialog(this, panel, "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            Sesija.getInstance().setUlogovani(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void btnUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUslugeActionPerformed
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem dodajUslugu = new JMenuItem("Dodaj uslugu");
        JMenuItem pretragaUsluga = new JMenuItem("Pronađi uslugu");

        dodajUslugu.addActionListener(e -> {
            new DodajUslugu(this, true).setVisible(true);
        });

        pretragaUsluga.addActionListener(e -> {
            new PretragaUsluga(this, true).setVisible(true);
        });

        popupMenu.add(dodajUslugu);
        popupMenu.add(pretragaUsluga);

        popupMenu.show(btnUsluge, btnUsluge.getWidth(), 0);
    }//GEN-LAST:event_btnUslugeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlijent;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnUgovori;
    private javax.swing.JButton btnUsluge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmn;
    // End of variables declaration//GEN-END:variables
}
